# Copyright 2019 Monetizr Inc.
#
# This file configures the middleware application . The frontend serves
# public web traffic.

# The bookshelf frontend replication controller ensures that at least 3
# instances of the bookshelf app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
# For more info about Deployments:
#   https://kubernetes.io/docs/user-guide/deployments/

# [START kubernetes_deployment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-tutorial
  labels:
    app: react-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-tutorial
  template:
    metadata:
      labels:
        app: react-tutorial
    spec:
      containers:
      - name: react-tutorial-app
        image: gcr.io/gcp-monetizr-project/react_tutorial:latest
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
# [END kubernetes_deployment]
